public class HelloAgain {
    
   public integer i;
    public integer j;
    
   public  string name;
 public integer display()
{
    system.debug('Welcome Again');
                 i=10;
                 j=20;
                 integer sum=i+j;
    system.debug('sum'+sum);
                 return sum;
}
    public integer display(integer i,integer j)
    {
       integer sum1=i+j;
           system.debug('sum1'+sum1);
          return sum1; 
    }
}